### ISSUE TITLE
Problem with import of module

### ISSUE THREAD

**Issue by ToFFmashines** [pyroll-project/pyroll-freiberg-flow-stress#2]
Hi,

I got this message (see below) at import of pyroll.basic module (import pyroll.basic as pr).
Installation of PyRoll I made by 
pip install pyroll

The version of modules are
pyroll 1.0.5.post1
pyroll-basic 1.0.1
pyroll-freiberg_flow_stress 1.1.1

Can you please tell me where the error is?

Best regards,
Tomas Kubina
Head of Roll Pass Design Department
Liberty Ostrava, Czech Republic

P.S.: We can communicate directly by e-mail tomas.kubina @ libertysteelgroup.com

Traceback (most recent call last):
  File "C:\Users\n029399\Python-Portable-3.9.6\apps\rolling\input.py", line 1, in <module>
    import pyroll.basic as pr
  File "C:\Users\n029399\Python-Portable-3.9.6\apps\lib\site-packages\pyroll\basic.py", line 7, in <module>
    import pyroll.freiberg_flow_stress as freiberg_flow_stress
  File "C:\Users\n029399\Python-Portable-3.9.6\apps\lib\site-packages\pyroll\freiberg_flow_stress\__init__.py", line 3, in <module>
    from . import hookspecs
  File "C:\Users\n029399\Python-Portable-3.9.6\apps\lib\site-packages\pyroll\freiberg_flow_stress\hookspecs.py", line 4, in <module>
    @RollPass.Profile.hookspec
AttributeError: type object 'Profile' has no attribute 'hookspec'

**Comment by ChRen95** [comment]
Hi Tomas, 
Sorry we currently have zero to no internet at the University so I didn't see your Issue.
To me this sounds like a version conflict. Please check if pyroll-core version 2.0 or higher is installed. If so please uninstall this version and reinstall pyroll-basic or pyroll whatever you are using. This should resolve your issue.
